name: cscorner
description: "Create and manage a to-do list"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.2  # Ensure this is compatible with your SDK
  timezone: ^0.9.0  # Ensure this is compatible with your SDK
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.otf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.otf
        - asset: fonts/Lato-Bold.otf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.otf
        - asset: fonts/OpenSans-Bold.otf
          weight: 700
